:set nocompatible
:set encoding=utf-8
:set relativenumber
:set autoindent
:set tabstop=4
:set shiftwidth=4
:set smarttab
:set softtabstop=4
:set mouse=a
:set clipboard+=unnamedplus
call plug#begin()

Plug 'https://github.com/vim-airline/vim-airline'
Plug 'https://github.com/preservim/nerdtree'
Plug 'https://github.com/tpope/vim-surround'
Plug 'https://github.com/jiangmiao/auto-pairs'
Plug 'https://github.com/alvan/vim-closetag'
Plug 'https://github.com/mhinz/vim-startify'
Plug 'https://github.com/nvim-treesitter/nvim-treesitter'
Plug 'https://github.com/catppuccin/nvim'
Plug 'https://github.com/jzelinskie/monokai-soda.vim'
Plug 'https://github.com/ellisonleao/gruvbox.nvim'
Plug 'https://github.com/christoomey/vim-system-copy'
Plug 'https://github.com/kdheepak/monochrome.nvim'
Plug 'shaunsingh/nord.nvim'
Plug 'https://github.com/ellisonleao/gruvbox.nvim'
call plug#end()

set background=dark
colorscheme gruvbox
