idle_bg = "#000000"
idle_fg = "#93a1a1"
info_bg = "#000000"
info_fg = "#93a1a1"
good_bg = "#000000"
good_fg = "#9d7cd8"
warning_bg  = "#000000"
warning_fg  = "#9d7cd8"
critical_bg = "#000000"
critical_fg = "#9d7cd8"
separator = "|"
separator_bg = "#1a1b26"
separator_fg = "#a9a9a9"
